/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.guimaraescouto.frames;

import br.com.guimaraescouto.dao.ClienteDAO;
import br.com.guimaraescouto.dao.PagamentoDAO;
import br.com.guimaraescouto.dao.ProdutoDAO;
import br.com.guimaraescouto.dao.UsuarioDAO;
import br.com.guimaraescouto.dao.VendaDAO;
import br.com.guimaraescouto.entity.Cliente;
import br.com.guimaraescouto.entity.ItemVenda;
import br.com.guimaraescouto.entity.Pagamento;
import br.com.guimaraescouto.entity.Produto;
import br.com.guimaraescouto.entity.Usuario;
import br.com.guimaraescouto.entity.Venda;
import static br.com.guimaraescouto.util.ConsideraEnterTab.considerarEnterComoTab;
import br.com.guimaraescouto.util.JMoneyFieldValor;
import br.com.guimaraescouto.util.MyCurrencyCellRenderer;
import br.com.guimaraescouto.util.MyGenericCellRenderer;
import br.com.guimaraescouto.util.MyTableModel;
import java.awt.AWTKeyStroke;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.KeyboardFocusManager;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import static javax.swing.SwingConstants.CENTER;
import sun.text.resources.FormatData;

/**
 *
 * @author Fábio
 */
public class frmVenda extends javax.swing.JDialog{
    
     private final VendaDAO vendaDAO = new VendaDAO(); 
     private final ClienteDAO clienteDAO = new ClienteDAO();
     private final ProdutoDAO produtoDAO = new ProdutoDAO();
     private final PagamentoDAO pagamentoDAO = new PagamentoDAO();
     private final UsuarioDAO atendenteDAO = new UsuarioDAO();
     private Cliente cliente = new Cliente(); 
     private Produto produto = new Produto();
     private Usuario atendente = new Usuario();
     private List<ItemVenda> itensVenda = new ArrayList<ItemVenda>();
     private int ordemItens = 1;
     private Integer quantidade;
     private final DecimalFormat df = new DecimalFormat( "#,##0.00" );
     private boolean flagFinalizar = false;
     
    /**
     * Creates new form frmVenda
     */
    public frmVenda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadInitialData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        btnPesquisarCliente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNumVenda = new javax.swing.JTextField();
        txtDataVenda = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCodBarras = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItensVenda = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtValorTotalVenda = new javax.swing.JTextField();
        btnPesquisarProduto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtValorPago = new javax.swing.JTextField();
        txtTroco = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnExcluirItem = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtValorUnitario = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txtAtendente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendas");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Cód Cliente:");

        txtCodCliente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtCodCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodClienteFocusLost(evt);
            }
        });
        txtCodCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodClienteActionPerformed(evt);
            }
        });
        txtCodCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodClienteKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Nome:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtNomeCliente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNomeCliente.setBorder(null);
        txtNomeCliente.setEnabled(false);

        btnPesquisarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesquisar.gif"))); // NOI18N
        btnPesquisarCliente.setAlignmentX(0.5F);
        btnPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(txtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(7, 7, 7))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Núm. Venda:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Data Venda:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtNumVenda.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNumVenda.setBorder(null);
        txtNumVenda.setEnabled(false);
        txtNumVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumVendaActionPerformed(evt);
            }
        });

        txtDataVenda.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtDataVenda.setBorder(null);
        txtDataVenda.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtNumVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(641, 641, 641))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNumVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Itens da Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Código Barras");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Valor Unitário");

        txtCodBarras.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtCodBarras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodBarrasFocusLost(evt);
            }
        });
        txtCodBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodBarrasKeyPressed(evt);
            }
        });

        tblItensVenda.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tblItensVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ITEM", "PRODUTO", "QUANTIDADE", "VALOR UNITÁRIO", "TOTAL"
            }
        ));
        tblItensVenda.setFocusable(false);
        tblItensVenda.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblItensVenda);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Sub Total:");

        txtValorTotalVenda.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtValorTotalVenda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorTotalVenda.setBorder(null);
        txtValorTotalVenda.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        txtValorTotalVenda.setEnabled(false);

        btnPesquisarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesquisar.gif"))); // NOI18N
        btnPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProdutoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Valor Pago:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Troco:");

        txtValorPago = new JMoneyFieldValor();
        txtValorPago.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtValorPago.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorPagoFocusLost(evt);
            }
        });

        txtTroco.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtTroco.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTroco.setBorder(null);
        txtTroco.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        txtTroco.setEnabled(false);
        txtTroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrocoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluirItem.setText("Excluir Item");
        btnExcluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirItemActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("F1 - Pesquisar Cliente");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("F2 - Pesquisar Produto");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("F3 - Salvar Venda");

        txtValorUnitario = new JMoneyFieldValor();
        txtValorUnitario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtValorUnitario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorUnitarioFocusLost(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText("Atendente:");

        txtAtendente.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAtendenteActionPerformed(evt);
            }
        });
        txtAtendente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAtendenteFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel8)))
                        .addGap(171, 171, 171)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExcluirItem))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvar)
                        .addGap(4, 4, 4)
                        .addComponent(btnCancelar))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(7, 7, 7))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtValorPago, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(txtValorTotalVenda)
                            .addComponent(txtTroco)
                            .addComponent(txtAtendente))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnExcluirItem)
                        .addGap(5, 5, 5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPesquisarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtValorTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(txtAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1252, 765));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodClienteActionPerformed

    private void btnPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarClienteActionPerformed
        // TODO add your handling code here:
        frmPesquisarCliente dialog = new frmPesquisarCliente(new javax.swing.JFrame(), true, this, null);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnPesquisarClienteActionPerformed

    public void refreshCliente(String id, String nome) {
        txtCodCliente.setText(id);
        txtNomeCliente.setText(nome);
        txtCodBarras.requestFocus();
    }
    
    public void refreshProduto(String codigoBarras) {
        txtCodBarras.setText(txtCodBarras.getText() + codigoBarras);
        txtCodBarras.requestFocus();
    }
    
    private void txtCodClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodClienteFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodClienteFocusGained

    private void txtCodClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodClienteFocusLost
         try {
             // TODO add your handling code here:
             cliente = clienteDAO.retornaClientePorId(new Integer(txtCodCliente.getText()));
             if(cliente.getId() != null){
                txtCodCliente.setText(cliente.getId().toString());
                txtNomeCliente.setText(cliente.getNome());
                txtCodBarras.requestFocus();
             }else{
                txtNomeCliente.setText("Cliente não encontrado.");
                txtCodCliente.requestFocus();
                
             }
             
         } catch (Exception ex) {
             txtNomeCliente.setText("Cliente não encontrado.");
             txtCodCliente.requestFocus();
         }
    }//GEN-LAST:event_txtCodClienteFocusLost

    private void txtCodBarrasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodBarrasFocusLost
        if(txtCodBarras.getText()!= null
                && !"".equals(txtCodBarras.getText())){ 
            try {
                 if(txtCodBarras.getText().contains("*")){
                     String[] split = txtCodBarras.getText().split("\\*");
                     if(split.length == 1){
                         txtCodBarras.requestFocus();
                         return;
                     }
                     produto = produtoDAO.retornaProdutoPorCodBarras(split[1]);
                     if(produto.getId() == null){
                         int result = JOptionPane.showConfirmDialog(this, "Produto não encontrado. Deseja adicionar?","Produto não encontrado",JOptionPane.OK_OPTION,JOptionPane.QUESTION_MESSAGE);
                         if(result == 0){
                             frmAdicionarProduto dialog = new frmAdicionarProduto(new javax.swing.JFrame(), true, produtoDAO,null,this);
                             dialog.setVisible(true);
                             txtCodBarras.requestFocus();
                             flagFinalizar = false;
                             return;
                         }else{
                             txtCodBarras.setText(null);
                             txtCodBarras.requestFocus();
                             flagFinalizar = false;
                             return;
                         }
                     }else{
                         if(produto.getSecao()){
                            txtValorUnitario.requestFocus();
                            flagFinalizar = false;
                            quantidade = new Integer(split[0]);
                            return;
                         }else{
                            quantidade = new Integer(split[0]);
                            insereItemVenda(produto);
                            txtCodBarras.setText(null);
                            txtCodBarras.requestFocus();
                            flagFinalizar = false;
                            return;
                        }
                     }
                 }else if(txtCodBarras.getText().toUpperCase().contains("P")){
                     txtCodBarras.setText(txtCodBarras.getText().toUpperCase().replace("P", ""));
                     produto = produtoDAO.retornaProdutoPorCodBarras(txtCodBarras.getText());
                     if(produto.getId() == null){
                         int result = JOptionPane.showConfirmDialog(this, "Produto não encontrado. Deseja adicionar?","Produto não encontrado",JOptionPane.OK_OPTION,JOptionPane.QUESTION_MESSAGE);
                         if(result == 0){
                             frmAdicionarProduto dialog = new frmAdicionarProduto(new javax.swing.JFrame(), true, produtoDAO,null,this );
                             dialog.setVisible(true);
                         }else{
                             txtCodBarras.setText(null);
                             txtCodBarras.requestFocus();
                             flagFinalizar = false;
                             return;
                         }
                     }
                     quantidade = new Integer(1);
                     txtValorUnitario.requestFocus();
                     flagFinalizar = false;
                     return;
                 }
                 // TODO add your handling code here:
                 produto = produtoDAO.retornaProdutoPorCodBarras(txtCodBarras.getText());
                 if(produto.getId() == null){
                    int result = JOptionPane.showConfirmDialog(this, "Produto não encontrado. Deseja adicionar?","Produto não encontrado",JOptionPane.OK_OPTION,JOptionPane.QUESTION_MESSAGE);
                    if(result == 0){
                        frmAdicionarProduto dialog = new frmAdicionarProduto(new javax.swing.JFrame(), true, produtoDAO,null,this );
                        dialog.setVisible(true);
                    }else{
                        txtCodBarras.setText(null);
                        txtCodBarras.requestFocus();
                        flagFinalizar = false;
                        return;
                    }
                 }
                 produto = produtoDAO.retornaProdutoPorCodBarras(txtCodBarras.getText());
                 quantidade = new Integer(1);
                 if(produto.getSecao()){
                     txtValorUnitario.requestFocus();
                     flagFinalizar = false;
                     return;
                 }else{
                     insereItemVenda(produto);
                     txtCodBarras.setText(null);
                     txtCodBarras.requestFocus();
                     flagFinalizar = false;
                     return;
                 }

             } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao tentar adicionar o item. Tente novamente.");
                txtCodBarras.setText(null);
                txtCodBarras.requestFocus();
                flagFinalizar = false;
                return;
             }
        }else{
            if(!flagFinalizar){
                txtCodBarras.requestFocus();
            }
        }
    }//GEN-LAST:event_txtCodBarrasFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        if (cliente == null
                || cliente.getId() == null) {
            JOptionPane.showMessageDialog(this, "Favor adicionar o cliente");
            txtCodCliente.requestFocus();
            return;
        }
        if (itensVenda == null
                || itensVenda.size() < 1) {
            JOptionPane.showMessageDialog(this, "Favor adicionar pelo menos um item.");
            txtCodBarras.requestFocus();
            return;
        }
        
        if (txtAtendente.getText() == null) {
            JOptionPane.showMessageDialog(this, "Atendente é obrigatório.");
            txtAtendente.requestFocus();
            return;
        }
        
        if (atendente.getId() == null) {
            JOptionPane.showMessageDialog(this, "Atendente não encontrado.");
            txtAtendente.requestFocus();
            return;
        }
        
        Venda venda = new Venda();
        venda.setId(new Integer(txtNumVenda.getText()));
        venda.setDataVenda(new java.sql.Date(new java.util.Date().getTime()));
        venda.setTotal(calcularTotalVenda(itensVenda));
        venda.setItens(itensVenda);
        for (ItemVenda itemVenda : itensVenda) {
            itemVenda.setVenda(venda);
        }
        venda.setCliente(cliente);
         try {
             vendaDAO.adicionarVenda(venda, true);
             setVisible(false);
         } catch (SQLException ex) {
             Logger.getLogger(frmVenda.class.getName()).log(Level.SEVERE, null, ex);
         }
         try {
            String valorPagoStr = txtValorPago.getText().replace(".", "");
            valorPagoStr = valorPagoStr.replace(",", ".");
            BigDecimal valorPago = new BigDecimal(valorPagoStr);
            Pagamento pagamento = new Pagamento();
            pagamento.setCliente(cliente);
            pagamento.setDataPagamento(new java.sql.Date(new java.util.Date().getTime()));
            pagamento.setValorPagamento(valorPago);
            pagamento.setUsuario(atendente);
            pagamentoDAO.adicionarPagamento(pagamento);
         } catch (SQLException ex) {
             Logger.getLogger(frmVenda.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProdutoActionPerformed
        // TODO add your handling code here:
        frmPesquisarProduto dialog = new frmPesquisarProduto(new javax.swing.JFrame(), true,  this);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnPesquisarProdutoActionPerformed

    private void txtTrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrocoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtValorPagoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorPagoFocusLost
        // TODO add your handling code here:
        String valorPago = txtValorPago.getText().replace(".", "");
        valorPago = valorPago.replace(",", ".");
        String valorTotalVenda = txtValorTotalVenda.getText().replace(".", "");
        valorTotalVenda = valorTotalVenda.replace(",", ".");
        txtTroco.setText(df.format((new BigDecimal(valorPago).subtract(new BigDecimal(valorTotalVenda)))));
    }//GEN-LAST:event_txtValorPagoFocusLost

    private void btnExcluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirItemActionPerformed
        // TODO add your handling code here:
        if(tblItensVenda.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "Selecione o item a ser removido.");
            return;
        }
        itensVenda.remove(tblItensVenda.getSelectedRow());
        Collections.reverse(itensVenda);
        int count = 1;
        for (ItemVenda itemVenda : itensVenda) {
           itemVenda.setOrdem(count);
           count++;
        }
        ordemItens = count;
        Collections.sort(itensVenda);
        tblItensVenda.setModel(new MyTableModel(ItemVenda.class, itensVenda,tblItensVenda));
        txtValorTotalVenda.setText(df.format(calcularTotalVenda(itensVenda)));
    }//GEN-LAST:event_btnExcluirItemActionPerformed

    private void txtCodClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodClienteKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1){
            frmPesquisarCliente dialog = new frmPesquisarCliente(new javax.swing.JFrame(), true, this, null);
            dialog.setVisible(true);
        }else if(evt.getKeyCode() == KeyEvent.VK_F3){
            flagFinalizar = true;
            txtValorPago.requestFocus();
        }
    }//GEN-LAST:event_txtCodClienteKeyPressed

    private void txtCodBarrasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodBarrasKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F2){
            frmPesquisarProduto dialog = new frmPesquisarProduto(new javax.swing.JFrame(), true, this);
            dialog.setVisible(true);
        }else if(evt.getKeyCode() == KeyEvent.VK_F3){
            flagFinalizar = true;
             txtValorPago.requestFocus();
        }
    }//GEN-LAST:event_txtCodBarrasKeyPressed

    private void txtNumVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumVendaActionPerformed

    private void txtValorUnitarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorUnitarioFocusLost
        // TODO add your handling code here:
        if(txtValorUnitario.getText() != null
                && !"".equals(txtValorUnitario.getText())){
           String preco = txtValorUnitario.getText().replace(".", "");
           preco = preco.replace(",", ".");
           produto.setPreco(new BigDecimal(preco));
           insereItemVenda(produto);
           txtCodBarras.setText(null);
           txtValorUnitario.setText(null);
           txtCodBarras.requestFocus();    
        }else{
            JOptionPane.showMessageDialog(this, "Favor adicionar o valor unitário.");
            txtValorUnitario.requestFocus();
            return;
        }
    }//GEN-LAST:event_txtValorUnitarioFocusLost

    private void txtAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAtendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAtendenteActionPerformed

    private void txtAtendenteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAtendenteFocusLost
        // TODO add your handling code here:
        if(txtAtendente.getText() != null){
            try {
                atendente = atendenteDAO.retornaUsuario(new Integer(txtAtendente.getText()));
            } catch (SQLException ex) {
                Logger.getLogger(frmVenda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtAtendenteFocusLost

    private void insereItemVenda(Produto produto){
        ItemVenda itemVenda = new ItemVenda();
        itemVenda.setOrdem(ordemItens++);
        itemVenda.setProduto(produto);
        itemVenda.setQuantidade(quantidade);
        itemVenda.setPrecoUnitario(produto.getPreco());
        itemVenda.setTotal(itemVenda.getTotal());
        itensVenda.add(itemVenda);
        Collections.sort(itensVenda);
        tblItensVenda.setModel(new MyTableModel(ItemVenda.class, itensVenda,tblItensVenda));
        tblItensVenda.setDefaultRenderer(Object.class, new MyGenericCellRenderer());
        txtValorTotalVenda.setText(df.format(calcularTotalVenda(itensVenda)));
    }
    
    public BigDecimal calcularTotalVenda(List<ItemVenda> itens){
        BigDecimal totalVenda = new BigDecimal(0);
        for (ItemVenda itemVendaSoma : itensVenda) {
            totalVenda = totalVenda.add(itemVendaSoma.getTotal());
        }
        return totalVenda;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmVenda dialog = new frmVenda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluirItem;
    private javax.swing.JButton btnPesquisarCliente;
    private javax.swing.JButton btnPesquisarProduto;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblItensVenda;
    private javax.swing.JTextField txtAtendente;
    private javax.swing.JTextField txtCodBarras;
    private javax.swing.JTextField txtCodCliente;
    private javax.swing.JTextField txtDataVenda;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNumVenda;
    private javax.swing.JTextField txtTroco;
    private javax.swing.JTextField txtValorPago;
    private javax.swing.JTextField txtValorTotalVenda;
    private javax.swing.JFormattedTextField txtValorUnitario;
    // End of variables declaration//GEN-END:variables

    private void loadInitialData() {
         try {
             txtNumVenda.setText(vendaDAO.retornaCodigoVenda().toString());
             txtValorTotalVenda.setText("0,00");
             txtValorPago.setText("0,00");
             txtTroco.setText("0,00");
             txtDataVenda.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));
             tblItensVenda.getTableHeader().setFont(new Font("Arial", Font.BOLD,17));
             considerarEnterComoTab(txtCodCliente);
             considerarEnterComoTab(txtCodBarras);
             considerarEnterComoTab(txtValorUnitario);
             considerarEnterComoTab(txtValorPago);
             considerarEnterComoTab(txtTroco);
             considerarEnterComoTab(txtAtendente);
             //Exibi na tela inteira
             Toolkit tk = Toolkit.getDefaultToolkit();
             Dimension screenSize = tk.getScreenSize();
             setSize(screenSize);
             setLocation((screenSize.width - this.getWidth()) / 2, (screenSize.height - this.getHeight()) / 2);
         } catch (SQLException ex) {
             Logger.getLogger(frmVenda.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
}
